In [22]:
 # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import time
import gmaps
import gmaps.datasets
import os

In [26]:
# Import API Keys
gmaps.configure(api_key="AIzaSyAy0zhRX2bbX4t_yLAxUqCjR45VzhpmtC4")

In [27]:
# Store Weather Py 

weather_df=pd.read_csv("Weather_Py.csv")
weather_df
weather_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Verkh-Usugli,88,RU,1610336591,84,52.7000,115.1667,-1.35,1.16
1,1,Mataura,77,NZ,1610336456,70,-46.1927,168.8643,57.99,14.00
2,2,Butaritari,100,KI,1610336417,81,3.0707,172.7902,81.46,19.19
3,3,Avera,1,US,1610336591,100,33.1940,-82.5271,37.99,3.44
4,4,Pailón,20,BO,1610336591,83,-17.6500,-62.7500,80.60,13.80

In [28]:
#humidity heatmap

locations = weather_df[["Lat", "Lng"]]
weights = weather_df["Humidity"]
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(height='420px'))

In [29]:
# Create Ideal Weather Data Frame
ideal_weather=weather_df[(weather_df["Max Temp"]<80)&(weather_df["Max Temp"]>70)&(weather_df["Wind Speed"]<10)&(weather_df["Cloudiness"]==0)]
ideal_weather

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
161,161,Rio Grande,0,BR,1610336512,86,-32.0350,-52.0986,77.00,3.00
181,181,Mamaku,0,NZ,1610336624,58,-38.1000,176.0833,78.01,7.00
235,235,Minna,0,NG,1610336633,21,9.6139,6.5569,72.81,8.48
242,242,Okato,0,NZ,1610336634,70,-39.2000,173.8833,75.00,5.01
247,247,Conakry,0,GN,1610336635,76,9.5380,-13.6773,78.67,9.22
279,279,Takoradze,0,GH,1610336378,89,4.8845,-1.7554,77.94,7.49
283,283,Kamakwie,0,SL,1610336641,83,9.5000,-12.2333,74.64,4.43
292,292,Mopti,0,ML,1610336642,35,14.6667,-4.0000,73.40,9.22
407,407,Hawera,0,NZ,1610336660,62,-39.5917,174.2833,75.00,6.91
513,513,Iquitos,0,PE,1610336663,94,-3.7481,-73.2472,75.20,1.86

In [12]:
# Create Hotel Data Frame 
hotel_df = ideal_weather
hotel_df.loc[:,("Hotel Name")] = np.nan
hotel_df

/Users/bucky/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/bucky/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
161,161,Rio Grande,0,BR,1610336512,86,-32.0350,-52.0986,77.00,3.00,NaN
181,181,Mamaku,0,NZ,1610336624,58,-38.1000,176.0833,78.01,7.00,NaN
235,235,Minna,0,NG,1610336633,21,9.6139,6.5569,72.81,8.48,NaN
242,242,Okato,0,NZ,1610336634,70,-39.2000,173.8833,75.00,5.01,NaN
247,247,Conakry,0,GN,1610336635,76,9.5380,-13.6773,78.67,9.22,NaN
279,279,Takoradze,0,GH,1610336378,89,4.8845,-1.7554,77.94,7.49,NaN
283,283,Kamakwie,0,SL,1610336641,83,9.5000,-12.2333,74.64,4.43,NaN
292,292,Mopti,0,ML,1610336642,35,14.6667,-4.0000,73.40,9.22,NaN
407,407,Hawera,0,NZ,1610336660,62,-39.5917,174.2833,75.00,6.91,NaN
513,513,Iquitos,0,PE,1610336663,94,-3.7481,-73.2472,75.20,1.86,NaN

In [15]:
hotellist = []

for i in range(len(ideal_weather)):
    lat = ideal_weather.loc[i]['Lat']
    lng = ideal_weather_df.loc[i]['Lng']

    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    requested = requests.get(base_url, params=params)
    jsn = requested.json()
    try:
        hotellist.append(jsn['results'][0]['name'])
    except:
        hotellist.append("")
narrowed_city_df["Hotel Name"] = hotellist
narrowed_city_df = narrowed_city_df.dropna(how='any')
narrowed_city_df.head()

KeyError: 0